---
- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items: "{{ database_partition_roller_yum_dependencies }}"

- name: Install tool
  include: installed.yml
  when: database_partition_roller_installed
